import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '../components/structuralComponents/header/Header'
import ContextComponent from '../context/ContextComponent'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Virdicon LTD Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextComponent>
        <Header></Header>
        {children}
        </ContextComponent>
        </body>
    </html>
  )
}
